---
kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: radarr-scc
fsGroup:
  type: RunAsAny
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
users:
- system:serviceaccount:{{.Release.Namespace}}:radarr-sa