apiVersion: v1
kind: Service
metadata:
  name: invidious
  labels:
    app: invidious
spec:
  type: ClusterIP
  ports:
    - port: 30000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: invidious
