app-template:
  controllers:
    main:
      type: statefulset
      annotations:
        reloader.stakater.com/auto: "true"
      labels:
        kasten/backup: "true"
      containers:
        main:
          image:
            # renovate: docker-image versioning=loose
            repository: ghcr.io/sct/overseerr
            tag: 1.33.2
            pullPolicy: IfNotPresent
          env:
            TZ: TIMEZONE

  serviceAccount:
    name: overseerr-sa

  service:
    main:
      controller: main
      ports:
        http:
          port: 5055

  persistence:
    config:
      enabled: true
      existingClaim: overseerr-config
      globalMounts:
        - path: /app/config

    data:
      enabled: true
      existingClaim: overseerr-data-volume
      globalMounts:
        - path: /data

  defaultPodOptions:
    securityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
        - 44
        - 109
        - 100
        - 65535
