app-template:
  controllers:
    main:
      type: statefulset
      annotations:
        reloader.stakater.com/auto: "true"
      containers:
        main:
          image:
            # renovate: docker-image versioning=loose
            repository: ghcr.io/sct/overseerr
            tag: 1.33.2
            pullPolicy: IfNotPresent
          env:
            TZ: TIMEZONE

  serviceAccount:
    name: overseerr-sa

  service:
    main:
      controller: main
      ports:
        http:
          port: 5055

  ingress:
    main:
      enabled: true
      annotations:
        forecastle.stakater.com/expose: "true"
        forecastle.stakater.com/icon: "https://raw.githubusercontent.com/sct/overseerr/develop/public/logo_full.svg"
        forecastle.stakater.com/appName: "overseerr"
        forecastle.stakater.com/group: "Media"
        route.openshift.io/termination: "edge"
      hosts:
        - host: &host "your_host"
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: main
                port: http

  persistence:
    config:
      enabled: true
      existingClaim: overseerr-config
      globalMounts:
        - path: /app/config

    data:
      enabled: true
      existingClaim: overseerr-data-volume
      globalMounts:
        - path: /data

  defaultPodOptions:
    securityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
        - 44
        - 109
        - 100
        - 65535
