config:
  storageClassName: "synology-iscsi"
  
app-template:
  controllers:
    main:
      type: statefulset
      annotations:
        reloader.stakater.com/auto: "true"
      labels:
        kasten/backup: "true"
      initContainers:
        config-fix:
          image: 
            repository: registry.hub.docker.com/library/alpine
            tag: 3.19.1
          #command: ["find", "/config", "-not", "-user", "1000", "-or", "-not", "-group", "1000", "-exec", "chown", "1000:1000", "{}", "+"]
          command: ["sh", "-c", 'if test -f /config/sabnzbd.ini; then sed -i "s/^host_whitelist.*/host_whitelist = $HOSTNAME/" /config/sabnzbd.ini; fi']
          env:
            HOSTNAME: HOSTNAME
          securityContext:
            readOnlyRootFilesystem: true
            runAsUser: 0
            runAsNonRoot: false
      containers:
        main:
          image:
            # renovate: docker-image versioning=loose
            repository: ghcr.io/onedr0p/sabnzbd
            tag: 4.2.3
            pullPolicy: IfNotPresent
          env:
            TZ: TIMEZONE

  serviceAccount:
    name: sabnzbd-sa

  service:
    main:
      controller: main
      ports:
        http:
          port: 8080

  persistence:
    config:
      enabled: true
      existingClaim: sabnzbd-config
      globalMounts:
        - path: /config

    data:
      enabled: true
      existingClaim: sabnzbd-data-volume
      globalMounts:
        - path: /data

  defaultPodOptions:
    securityContext:
      runAsUser: 0
      runAsGroup: 0
      fsGroup: 0
