config:
  storageClassName: "synology-iscsi"
  
app-template:
  controllers:
    main:
      type: statefulset
      annotations:
        reloader.stakater.com/auto: "true"
      labels:
        kasten/backup: "true"
      containers:
        main:
          image:
            # renovate: docker-image versioning=loose
            repository: ghcr.io/onedr0p/bazarr
            tag: 1.4.2
            pullPolicy: IfNotPresent
          env:
            TZ: TIMEZONE
  serviceAccount:
    name: bazarr-sa

  service:
    main:
      controller: main
      ports:
        http:
          port: 6767

  persistence:
    config:
      enabled: true
      existingClaim: bazarr-config

    data:
      enabled: true
      existingClaim: bazarr-data-volume
      globalMounts:
        - path: /data

  defaultPodOptions:
    labels:
      sidecar.istio.io/inject: "true"
    securityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
        - 44
        - 109
        - 100
        - 65535
