app-template:
  securityContext:
    privileged: true
  controllers:
    main315:
      type: statefulset
      strategy: RollingUpdate
      annotations:
        reloader.stakater.com/auto: "true"
      labels:
        kasten/backup: "true"
      containers:
        main315:
          securityContext:
            privileged: true
          image:
            # renovate: docker-image versioning=loose
            repository: hertzg/rtl_433
            tag: latest
            pullPolicy: Always
          args:
           - -d 0
           - -S all
           - -v
           - -M level
           - -f 315000000 
    main433:
      type: statefulset
      strategy: RollingUpdate
      annotations:
        reloader.stakater.com/auto: "true"
      labels:
        kasten/backup: "true"
      containers:
        main433:
          securityContext:
            privileged: true
          image:
            # renovate: docker-image versioning=loose
            repository: hertzg/rtl_433
            tag: latest
            pullPolicy: Always
          args:
           - -d 1
           - -S all
           - -v
           - -M level
           - -f 433000000 

  serviceAccount:
    name: rtl433-sa

  defaultPodOptions:
    labels:
      app: rtl433
      version: 1.0.0
    securityContext:
      runAsUser: 0
      runAsGroup: 0
      fsGroup: 0
    nodeSelector:
      nesdr.feature.node.kubernetes.io/rtlamr: "true"