apiVersion: nmstate.io/v1
kind: NMState
metadata:
  name: nmstate
spec: {}
---
apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: master-0-storage-ip
spec:
  desiredState:
    interfaces:
      - ipv4:
          address:
            - ip: {{ .Values.network.master-0.storage-ip.ip }}
              prefix-length: {{ .Values.network.master-0.storage-ip.prefix-length }}
          enabled: true
        name: {{ .Values.network.master-0.storage-interface.name }}
        state: up
        type: ethernet
  nodeSelector:
    kubernetes.io/hostname: master-0
---
apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: master-1-storage-ip
spec:
  desiredState:
    interfaces:
      - ipv4:
          address:
            - ip: {{ .Values.network.master-0.storage-ip.ip }}
              prefix-length: {{ .Values.network.master-0.storage-ip.prefix-length }}
          enabled: true
        name: {{ .Values.network.master-0.storage-interface.name }}
        state: up
        type: ethernet
  nodeSelector:
    kubernetes.io/hostname: master-1
---
apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: master-2-storage-ip
spec:
  desiredState:
    interfaces:
      - ipv4:
          address:
            - ip: {{ .Values.network.master-0.storage-ip.ip }}
              prefix-length: {{ .Values.network.master-0.storage-ip.prefix-length }}
          enabled: true
        name: {{ .Values.network.master-0.storage-interface.name }}
        state: up
        type: ethernet
  nodeSelector:
    kubernetes.io/hostname: master-2
