app-template:
  controllers:
    main:
      type: deployment
      replicas: 3
      strategy: RollingUpdate
      annotations:
        reloader.stakater.com/auto: "true"
      labels:
        kasten/backup: "true"
      containers:
        main:
          image:
            # renovate: docker-image versioning=loose
            repository: ghcr.io/ullbergm/hajimari
            tag: latest
            pullPolicy: Always
          env:
            TZ: TIMEZONE
          startupProbe:
            httpGet:
              path: /
              port: 3000
            failureThreshold: 3
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            timeoutSeconds: 10

  serviceAccount:
    name: hajimari-sa

  service:
    main:
      controller: main
      ports:
        http:
          port: 3000

  defaultPodOptions:
    labels:
      app: hajimari
      version: 1.0.0
    securityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
        - 44
        - 109
        - 100
        - 65535

  persistence:
    config:
      enabled: true
      type: configMap
      name: hajimari-config
      globalMounts:
        - path: /config/config.yaml
          subPath: config.yaml
          readOnly: true

hajimari:
    defaultEnable: true
    theme: null
    lightTheme: gazette
    darkTheme: blackboard
    showGreeting: false
    showAppGroups: true
    showAppInfo: true
    showAppUrls: false
    showBookmarkGroups: true
    showGlobalBookmarks: true
    alwaysTargetBlank: false
    targetBlank: false
    name: "friend"
    namespaceSelector:
      any: true