---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: data-volume
provisioner: nfs
parameters:
  archiveOnDelete: "false"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-volume
spec:
  storageClassName: media
  capacity:
    storage: 1Mi # Size does not matter
  accessModes: ["ReadWriteMany"]
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: nas.${SECRET_TLD}
    path: /volume1/kubernetes/data
  mountOptions:
    - nfsvers=4.2
    - nconnect=8
    - hard
    - noatime
    - rsize=131072
    - wsize=131072
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-volume
  namespace: media
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: data-volume
  resources:
    requests:
      storage: 1Mi # Size does not matter