---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-volume
spec:
  storageClassName: ""
  capacity:
    storage: 1Mi
  accessModes: ["ReadWriteMany"]
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: nas.${SECRET_TLD}
    path: /volume1/kubernetes/data
  mountOptions:
    - nfsvers=4.2
    - nconnect=8
    - hard
    - noatime
    - rsize=131072
    - wsize=131072
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-volume
  namespace: default
spec:
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 1Mi
  volumeName: data-volume
  storageClassName: ""