---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Namespace
  - namespace.yaml
  # SCC
  - scc.yaml
  # iSCSId
  - enable-iscsid.yaml
  # Secret
  - client-info-secret.sops.yaml
  # Driver
  - controller.yaml
  - csi-driver.yaml
  - node.yaml
  - storage-class.yaml
  - snapshotter.yaml
  - volume-snapshot-class.yaml