global:
  enabled: true
    
certificates:
  global:
    enabled: true

  cluster:
    top_level_domain: example.com
    name: my-cluster
    admin_email: magnus@ullberg.us

  issuer: staging # or production
  aws:
    region: us-east-1
    hosted_zone_id: YOUR_HOSTED_ZONE_ID
    access_key_id: YOUR_ACCESS_KEY_ID
    access_key_secret: YOUR_SECRET_ACCESS_KEY