apiVersion: hajimari.io/v1alpha1
kind: Application
metadata:
  name: sabnzbd
spec:
  name: Sabnzbd
  group: Downloading
  icon: download-box
  url: https://sabnzbd.apps.{{ .Values.cluster.name }}.{{ .Values.cluster.top_level_domain }}
  info: Efficient Usenet downloader
  targetBlank: true
---
apiVersion: console.openshift.io/v1
kind: ConsoleLink
metadata:
  name: sabnzbd-application-menu-link
spec:
  href: https://sabnzbd.apps.{{ .Values.cluster.name }}.{{ .Values.cluster.top_level_domain }}
  location: ApplicationMenu
  applicationMenu:
    section: "Downloading Tools"
    imageURL: https://raw.githubusercontent.com/sabnzbd/sabnzbd/develop/icons/logo-arrow.svg
  text: 'Sabnzbd'
---
apiVersion: console.openshift.io/v1
kind: ConsoleLink
metadata:
  name: sabnzbd-namespace-dashboard-link
spec:
  href: https://sabnzbd.apps.{{ .Values.cluster.name }}.{{ .Values.cluster.top_level_domain }}
  location: NamespaceDashboard
  namespaceDashboard:
    namespaces:
      - sabnzbd
  text: 'Access Application'