---
kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: lidarr-scc
fsGroup:
  type: RunAsAny
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
users:
- system:serviceaccount:media:lidarr-sa