apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: nfd
  namespace: openshift-nfd
spec:
  channel: stable 
  name: nfd 
  source: community-operators 
  sourceNamespace: openshift-marketplace 
  installPlanApproval: Automatic
