storage:
  data:
    storageClassName: synology-iscsi

app-template:
  controllers:
    main:
      type: statefulset
      strategy: RollingUpdate
      annotations:
        reloader.stakater.com/auto: "true"
      labels:
        kasten/backup: "true"
        app: mosquitto
        version: 1.0.0
      containers:
        main:
          image:
            # renovate: docker-image
            repository: public.ecr.aws/docker/library/eclipse-mosquitto
            tag: 2.0.18
            pullPolicy: Always
          args:
          - sh
          - -c
          - exec mosquitto -c "/config/$(hostname).conf"
          probes:
            liveness:
              enabled: true
            readiness:
              enabled: true
            startup:
              enabled: true
              spec:
                failureThreshold: 30
                periodSeconds: 5

  service:
    main:
      controller: main
      labels:
        keepalived-operator.redhat-cop.io/keepalivedgroup: keepalived-operator/lan
      annotations:
        coredns.io/hostname: mqtt
      externalIPs:
        - 192.168.0.100
      ports:
        mqtt:
          enabled: true
          port: 1883

  serviceAccount:
    name: mosquitto-sa

  persistence:
    data:
      existingClaim: mosquitto-data
      advancedMounts:
        main:
          main:
            - path: /data

    config:
      name: mosquitto-config
      type: configMap

  defaultPodOptions:
    securityContext:
      runAsUser: 2000
      runAsGroup: 2000
      fsGroup: 2000