config:
  storageClassName: "synology-iscsi"
  
app-template:
  controllers:
    main:
      type: statefulset
      annotations:
        reloader.stakater.com/auto: "true"
      labels:
        kasten/backup: "true"
      containers:
        main:
          image:
            # renovate: docker-image versioning=loose
            repository: ghcr.io/onedr0p/lidarr
            tag: 2.2.5.4141
            pullPolicy: IfNotPresent
          env:
            TZ: TIMEZONE

  serviceAccount:
    name: lidarr-sa

  service:
    main:
      controller: &controller main
      ports:
        http:
          port: &port 8686

  persistence:
    config:
      enabled: true
      existingClaim: lidarr-config

    data:
      enabled: true
      existingClaim: lidarr-data-volume
      globalMounts:
        - path: /data

  defaultPodOptions:
      sidecar.istio.io/inject: "true"
      app: lidarr
      version: 1.0.0
    securityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
        - 44
        - 109
        - 100
        - 65535
