app-template:
  controllers:
    main:
      type: statefulset
      annotations:
        reloader.stakater.com/auto: "true"
      labels:
        kasten/backup: "true"
      containers:
        main:
          image:
            # renovate: docker-image versioning=loose
            repository: ghcr.io/onedr0p/lidarr
            tag: 2.2.5.4141
            pullPolicy: IfNotPresent
          env:
            TZ: TIMEZONE

  serviceAccount:
    name: lidarr-sa

  service:
    main:
      controller: &controller main
      ports:
        http:
          port: &port 8686

  route:
    main:
      enabled: true
      annotations:
        forecastle.stakater.com/expose: "true"
        forecastle.stakater.com/icon: "https://raw.githubusercontent.com/Lidarr/Lidarr/develop/Logo/400.png"
        forecastle.stakater.com/appName: "lidarr"
        forecastle.stakater.com/group: "Media"
        route.openshift.io/termination: "edge"
      hostnames:
        - &host "your_host"
    rules:
      - matches:
          - path:
              type: PathPrefix
              value: /
        backendRefs:
          - kind: Service
            port: *port
            name: *controller
            namespace: default
            weight: 1

  persistence:
    config:
      enabled: true
      existingClaim: lidarr-config

    data:
      enabled: true
      existingClaim: lidarr-data-volume
      globalMounts:
        - path: /data

  defaultPodOptions:
    securityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
        - 44
        - 109
        - 100
        - 65535
