---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ tpl .Values.application.name . | lower }}-config"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.config.storageClassName }}
  resources:
    requests:
      storage: 15Gi