---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ index .Values "app-template" "persistence.config.existingClaim" }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storage.config.storageClassName }}
  resources:
    requests:
      storage: 15Gi