---
kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: "{{ tpl .Values.application.name . | lower }}-scc"
fsGroup:
  type: RunAsAny
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
users:
- "system:serviceaccount:{{.Release.Namespace}}:{{ tpl .Values.application.name . | lower }}-sa"