config:
  storageClassName: "synology-iscsi"
  
app-template:
  controllers:
    main:
      type: statefulset
      annotations:
        reloader.stakater.com/auto: "true"
      labels:
        kasten/backup: "true"
      containers:
        main:
          image:
            # renovate: docker-image
            repository: ghcr.io/k8s-at-home/readarr
            tag: v0.1.1.1352
            pullPolicy: IfNotPresent
          env:
            TZ: TIMEZONE

  serviceAccount:
    name: readarr-sa

  service:
    main:
      controller: main
      ports:
        http:
          port: 9696

  persistence:
    config:
      enabled: true
      existingClaim: readarr-config

    data:
      enabled: true
      existingClaim: readarr-data-volume
      globalMounts:
        - path: /data

  defaultPodOptions:
    labels:
      sidecar.istio.io/inject: "true"
      app: readarr
      version: 1.0.0
    securityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
        - 44
        - 109
        - 100
        - 65535
