config:
  storageClassName: "synology-iscsi"
  
app-template:
  controllers:
    main:
      type: statefulset
      annotations:
        reloader.stakater.com/auto: "true"
      labels:
        kasten/backup: "true"
      containers:
        main:
          image:
            # renovate: docker-image versioning=loose
            repository: ghcr.io/onedr0p/tautulli
            tag: 2.13.4
            pullPolicy: IfNotPresent
          env:
            TZ: TIMEZONE

  serviceAccount:
    name: tautulli-sa

  service:
    main:
      controller: main
      ports:
        http:
          port: 9696

  persistence:
    config:
      enabled: true
      existingClaim: tautulli-config

    data:
      enabled: true
      existingClaim: tautulli-data-volume
      globalMounts:
        - path: /data

  defaultPodOptions:
    securityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
        - 44
        - 109
        - 100
        - 65535
