app-template:
  controllers:
    main:
      type: statefulset
      annotations:
        reloader.stakater.com/auto: "true"
      containers:
        main:
          image:
            # renovate: docker-image versioning=loose
            repository: ghcr.io/onedr0p/tautulli
            tag: 2.13.4
            pullPolicy: IfNotPresent
          env:
            TZ: TIMEZONE

  serviceAccount:
    name: tautulli-sa

  service:
    main:
      controller: main
      ports:
        http:
          port: 9696

  ingress:
    main:
      enabled: true
      annotations:
        forecastle.stakater.com/expose: "true"
        forecastle.stakater.com/icon: "https://tautulli.com/images/logo.svg"
        forecastle.stakater.com/appName: "tautulli"
        forecastle.stakater.com/group: "Media"
        route.openshift.io/termination: "edge"
      hosts:
        - host: &host "your_host"
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: main
                port: http

  persistence:
    config:
      enabled: true
      existingClaim: tautulli-config

    data:
      enabled: true
      existingClaim: tautulli-data-volume
      globalMounts:
        - path: /data

  defaultPodOptions:
    securityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
        - 44
        - 109
        - 100
        - 65535
