---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config
  labels:
    kasten/skip: "true"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.config.storageClassName }}
  resources:
    requests:

      storage: 15Gi
