kind: Route
apiVersion: route.openshift.io/v1
metadata:
  annotations:
    forecastle.stakater.com/expose: "true"
    forecastle.stakater.com/icon: "https://tautulli.com/images/logo.svg"
    forecastle.stakater.com/appName: "tautulli"
    forecastle.stakater.com/group: "Media"
    route.openshift.io/termination: "edge"
  name: tautulli
  namespace: tautulli
spec:
  host: tautulli.apps.{{ .Values.cluster.name }}.{{ .Values.cluster.top_level_domain }}
  path: /
  to:
    kind: Service
    name: media-tautulli
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
