---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./api.yaml
  - ./apps.yaml
patches:
 - target:
    group: operator.openshift.io
    version: v1
    kind: IngressController
    name: default
    namespace: openshift-ingress-operator
   patch: |
    - op: add
      path: /spec/defaultCertificate
      value:
        name: apps-wildcard-cert-tls