app-template:
  securityContext:
    privileged: true
  controllers:
    main:
      type: statefulset
      strategy: RollingUpdate
      annotations:
        reloader.stakater.com/auto: "true"
      labels:
        kasten/backup: "true"
      containers:
        main:
          securityContext:
            privileged: true
          image:
            # renovate: docker-image versioning=loose
            repository: hertzg/rtl_433
            tag: latest
            pullPolicy: Always
          args:
           - -v
           - -M level
           - -f 315000000 
          env:
            TZ: TIMEZONE
            LISTEN_ONLY: yes
            RTL_MSGTYPE: all

  serviceAccount:
    name: rtlamr2mqtt-sa

  defaultPodOptions:
    labels:
      app: rtlamr2mqtt
      version: 1.0.0
    securityContext:
      runAsUser: 0
      runAsGroup: 0
      fsGroup: 0
    nodeSelector:
      nesdr.feature.node.kubernetes.io/rtlamr: "true"