cluster:
  top_level_domain: example.com
  name: openshift
  admin_email: admin@example.com
  timezone: &timezone America/New_York

application:
  name: App
  group: Media
  icon: simple-icons:app
  image: https://raw.githubusercontent.com/app/app/develop/Logo/400.png
  description: "A tool for managing stuff."
  port: 8080

storage:
  storageClassName: synology-iscsi
  media:
    nfs:
      server: nas
      path: /volume1/media

image:
  # renovate: docker-image versioning=loose
  repository: ghcr.io/onedr0p/app
  tag: 1.0.0.0000
  pullPolicy: IfNotPresent

## Define app-template parameters based on the values above

app-template:
  controllers:
    main:
      type: statefulset
      annotations:
        reloader.stakater.com/auto: "true"
      labels:
        kasten/backup: "true"
      containers:
        main:
          image:
            # renovate: docker-image versioning=loose
            repository: ghcr.io/onedr0p/app
            tag: 1.0.0.0000
            pullPolicy: IfNotPresent
          env:
            TZ: America/New_York

  serviceAccount:
    name: "{{ .Release.Name }}-sa"
