---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clusterplex-config-pvc
  labels:
    app.kubernetes.io/name: clusterplex-config-pvc
    app.kubernetes.io/part-of: clusterplex
    kasten/backup: "true"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: "15Gi"
  storageClassName: synology-iscsi
