kind: Route
apiVersion: route.openshift.io/v1
metadata:
  annotations:
    forecastle.stakater.com/expose: "true"
    forecastle.stakater.com/icon: "https://raw.githubusercontent.com/Sonarr/Sonarr/develop/Logo/400.png"
    forecastle.stakater.com/appName: "Sonarr"
    forecastle.stakater.com/group: "Media"
    route.openshift.io/termination: "edge"
  name: sonarr
  namespace: sonarr
spec:
  host: sonarr.apps.{{ .Values.cluster.name }}.{{ .Values.cluster.top_level_domain }}
  path: /
  to:
    kind: Service
    name: media-sonarr
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
