apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  generateName: openshift-kmm-hub-
  annotations:
    olm.providedAPIs: ManagedClusterModule.v1beta1.hub.kmm.sigs.x-k8s.io
  name: openshift-kmm-hub-cluster
  namespace: openshift-kmm-hub
spec:
  targetNamespaces:
    - openshift-kmm-hub
  upgradeStrategy: Default
