app-template:
  controllers:
    main:
      type: statefulset
      annotations:
        reloader.stakater.com/auto: "true"
      labels:
        kasten/backup: "true"
      containers:
        main:
          image:
            # renovate: docker-image
            repository: jvmilazz0/kavita
            tag: 0.8.1
            pullPolicy: IfNotPresent
          env:
            TZ: TIMEZONE

  serviceAccount:
    name: kavita-sa

  service:
    main:
      controller: main
      ports:
        http:
          port: 5000

  persistence:
    config:
      enabled: true
      existingClaim: kavita-config
      globalMounts:
      - path: /kavita/config

    data:
      enabled: true
      existingClaim: kavita-data-volume
      globalMounts:
        - path: /data

  defaultPodOptions:
    securityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
        - 44
        - 109
        - 100
        - 65535
