---
apiVersion: apik10.kasten.io/v1alpha1
kind: K10
metadata:
  name: k10
  namespace: kasten-io
spec:
  auth:
    basicAuth:
      enabled: false
      htpasswd: ''
      secretName: ''
    tokenAuth:
      enabled: true
  global:
    persistence:
      catalog:
        size: ''
      storageClass: ''
  metering:
    mode: ''
  route:
    enabled: true
    tls:
      enabled: true
