apiVersion: hajimari.io/v1alpha1
kind: Application
metadata:
  name: kavita
spec:
  name: Kavita
  group: Media
  icon: book
  url: https://kavita.apps.{{ .Values.cluster.name }}.{{ .Values.cluster.top_level_domain }}
  info: Manga reader
  targetBlank: true
---
apiVersion: console.openshift.io/v1
kind: ConsoleLink
metadata:
  name: kavita-application-menu-link
spec:
  href: https://kavita.apps.{{ .Values.cluster.name }}.{{ .Values.cluster.top_level_domain }}
  location: ApplicationMenu
  applicationMenu:
    section: "Media Tools"
    imageURL: https://raw.githubusercontent.com/Kareadita/Kavita/develop/Logo/kavita.svg
  text: 'Kavita'
---
apiVersion: console.openshift.io/v1
kind: ConsoleLink
metadata:
  name: kavita-namespace-dashboard-link
spec:
  href: https://kavita.apps.{{ .Values.cluster.name }}.{{ .Values.cluster.top_level_domain }}
  location: NamespaceDashboard
  namespaceDashboard:
    namespaces:
      - kavita
  text: 'Access Application'