---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kavita-config
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.config.storageClassName }}
  resources:
    requests:
      storage: 15Gi