---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kavita-config
  labels:
    kasten/backup: "true"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: synology-iscsi
  resources:
    requests:
      storage: 15Gi