kind: Route
apiVersion: route.openshift.io/v1
metadata:
  annotations:
    forecastle.stakater.com/expose: "true"
    forecastle.stakater.com/icon: "https://raw.githubusercontent.com/Kareadita/Kavita/develop/Logo/kavita.svg"
    forecastle.stakater.com/appName: "kavita"
    forecastle.stakater.com/group: "Media"
    route.openshift.io/termination: "edge"
  name: kavita
  namespace: kavita
spec:
  host: kavita.apps.{{ .Values.cluster.name }}.{{ .Values.cluster.top_level_domain }}
  path: /
  to:
    kind: Service
    name: media-kavita
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
