apiVersion: hajimari.io/v1alpha1
kind: Application
metadata:
  name: gaps
spec:
  name: Gaps
  group: Media
  icon: tag-search
  url: https://gaps.apps.{{ .Values.cluster.name }}.{{ .Values.cluster.top_level_domain }}
  info: Helps find missing movies in a series
  targetBlank: true