kind: Route
apiVersion: route.openshift.io/v1
metadata:
  annotations:
    forecastle.stakater.com/expose: "true"
    forecastle.stakater.com/icon: "https://raw.githubusercontent.com/JasonHHouse/gaps/master/images/Final-Black.png"
    forecastle.stakater.com/appName: "Gaps"
    forecastle.stakater.com/group: "Media"
    route.openshift.io/termination: "edge"
  name: gaps
  namespace: gaps
spec:
  host: gaps.apps.{{ .Values.cluster.name }}.{{ .Values.cluster.top_level_domain }}
  path: /
  to:
    kind: Service
    name: media-gaps
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
