apiVersion: hajimari.io/v1alpha1
kind: Application
metadata:
  name: prowlarr
spec:
  name: Prowlarr
  group: Media
  icon: cloud-search
  url: https://prowlarr.apps.{{ .Values.cluster.name }}.{{ .Values.cluster.top_level_domain }}
  info: Indexer manager/proxy
  targetBlank: true
---
apiVersion: console.openshift.io/v1
kind: ConsoleLink
metadata:
  name: prowlarr-application-menu-link
spec:
  href: https://prowlarr.apps.{{ .Values.cluster.name }}.{{ .Values.cluster.top_level_domain }}
  location: ApplicationMenu
  applicationMenu:
    section: "Media Tools"
    imageURL: https://raw.githubusercontent.com/Prowlarr/Prowlarr/develop/Logo/400.png
  text: 'Prowlarr'
---
apiVersion: console.openshift.io/v1
kind: ConsoleLink
metadata:
  name: prowlarr-namespace-dashboard-link
spec:
  href: https://prowlarr.apps.{{ .Values.cluster.name }}.{{ .Values.cluster.top_level_domain }}
  location: NamespaceDashboard
  namespaceDashboard:
    namespaces:
      - prowlarr
  text: 'Access Application'