kind: Route
apiVersion: route.openshift.io/v1
metadata:
  annotations:
    forecastle.stakater.com/expose: "true"
    forecastle.stakater.com/icon: "https://raw.githubusercontent.com/Prowlarr/Prowlarr/develop/Logo/400.png"
    forecastle.stakater.com/appName: "Prowlarr"
    forecastle.stakater.com/group: "Media"
    route.openshift.io/termination: "edge"
  name: prowlarr
  namespace: prowlarr
spec:
  host: prowlarr.apps.{{ .Values.cluster.name }}.{{ .Values.cluster.top_level_domain }}
  path: /
  to:
    kind: Service
    name: media-prowlarr
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
