forecastle:
  forecastle:
    route:  
      enabled: true
      annotations: {}
      additionalLabels: {}
      name: "www"
      port:
        targetPort: http
      wildcardPolicy: None
      tls:
        termination: edge
        insecureEdgeTerminationPolicy: Redirect
    config:
      namespaceSelector:
        - default