kind: Route
apiVersion: route.openshift.io/v1
metadata:
  annotations:
      forecastle.stakater.com/expose: "true"
      forecastle.stakater.com/icon: "https://raw.githubusercontent.com/sct/overseerr/develop/public/logo_full.svg"
      forecastle.stakater.com/appName: "overseerr"
      forecastle.stakater.com/group: "Media"
      route.openshift.io/termination: "edge"
  name: overseerr
  namespace: overseerr
spec:
  host: overseerr.apps.{{ .Values.cluster.name }}.{{ .Values.cluster.top_level_domain }}
  path: /
  to:
    kind: Service
    name: media-overseerr
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
