spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: YOUR_REPO_URL
    targetRevision: HEAD

cluster:
  top_level_domain: example.com
  name: my-cluster
  admin_email: YOUR_EMAIL
  timezone: YOUR_TIMEZONE

certificates:
  issuer: staging # or production
  aws:
    region: YOUR_REGION
    hosted_zone_id: YOUR_HOSTED_ZONE_ID
    access_key_id: YOUR_ACCESS_KEY_ID
    secret_access_key: YOUR_SECRET_ACCESS_KEY

democratic-csi:
  driver:
    config:
      httpConnection:
        host: my-nas
        password: my-password
        username: my-username
      iscsi:
        targetPortal: 'my-server[:port]'

config:
  storageClassName: "synology-iscsi"

media:
  nfs:
    server: my-nas
    path: /mnt/nfs

backup:
  nfs:
    server: my-nas
    path: /mnt/nfs

network:
  startIP: 192.168.64.55
  endIP: 192.168.64.59
  plexIP: 192.168.64.49
  node0:
    name: master-0
    storageInterface:
      name: enp2s0
    storageIp:
      ip: 10.0.0.1
      prefix-length: 24
  node1:
    name: master-1
    storageInterface:
      name: enp2s0
    storageIp:
      ip: 10.0.0.2
      prefix-length: 24
  node2:
    name: master-2
    storageInterface:
      name: enp2s0
    storageIp:
      ip: 10.0.0.3
      prefix-length: 24