---
kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: generic-device-plugin-scc
allowPrivilegedContainer: true
allowHostDirVolumePlugin: true
fsGroup:
  type: RunAsAny
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
users:
- system:serviceaccount:{{.Release.Namespace}}:generic-device-plugin-sa