apiVersion: hajimari.io/v1alpha1
kind: Application
metadata:
  name: bazarr
spec:
  name: Bazarr
  group: Media
  icon: simple-icons:subtitles
  url: https://bazarr.apps.{{ .Values.cluster.name }}.{{ .Values.cluster.top_level_domain }}
  info: Manages subtitles
  targetBlank: true