apiVersion: v1
kind: ConfigMap
metadata:
  name: hajimari-config
  namespace: hajimari
data:
  config.yaml: |-
    # Hajimari configuration file
    #
    hajimari:
        defaultEnable: true
        theme: null
        lightTheme: gazette
        darkTheme: blackboard
        showGreeting: false
        showAppGroups: true
        showAppInfo: true
        showAppUrls: false
        showBookmarkGroups: true
        targetBlank: false
        name: "friend"
