---
apiVersion: v1
kind: ConfigMap
metadata:
    name: hajimari-config
    namespace: default
data:
    config.yaml: |
        name: "Friend"
        title: Apps
        darkTheme: blackboard
        alwaysTargetBlank: false
        showGreeting: false
        showAppGroups: true
        showAppStatus: false
        showBookmarkGroups: false
        showGlobalBookmarks: false
        showAppUrls: false
        defaultEnable: true
        namespaceSelector:
        matchNames:
            - default
            - downloads
            - home
            - media
