kind: Route
apiVersion: route.openshift.io/v1
metadata:
  annotations:
    hajimari.io/enable: "false"
    hajimari.io/icon: "weather-sunset"
    route.openshift.io/termination: "edge"
  name: hajimari
  namespace: hajimari
spec:
  host: apps.{{ .Values.cluster.name }}.{{ .Values.cluster.top_level_domain }}
  path: /
  to:
    kind: Service
    name: hajimari
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
