apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-metallb-config
  namespace: openshift-gitops
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: charts/metallb-config
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      parameters:
        - name: network.startIP
          value: {{ .Values.network.startIP }}
        - name: network.endIP
          value: {{ .Values.network.endIP }}
        - name: network.plexIP
          value: {{ .Values.network.plexIP }}
  syncPolicy:
    automated:
      selfHeal: true