apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-democratic-csi-snapshot-controller
  namespace: openshift-gitops
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: democratic-csi
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: charts/democratic-csi-snapshot-controller
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true