apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: media-bazarr
  namespace: openshift-gitops
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: bazarr
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: charts/bazarr
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      parameters:
        - name: cluster.top_level_domain
          value: {{ .Values.cluster.top_level_domain }}
        - name: cluster.name
          value: {{ .Values.cluster.name }}
        - name: cluster.admin_email
          value: {{ .Values.cluster.admin_email }}
        - name: 'app-template.ingress.main.hosts[0].host'
          value: bazarr.apps.{{ .Values.cluster.name }}.{{ .Values.cluster.top_level_domain }}
        - name: app-template.controllers.main.containers.main.env.TZ
          value: {{ .Values.cluster.timezone }}
        - name: media.nfs.server
          value: {{ .Values.media.nfs.server }}
        - name: media.nfs.path
          value: {{ .Values.media.nfs.path }}
        - name: 'app-template.ingress.main.hosts[0].paths[0].path'
          value: /
        - name: 'app-template.ingress.main.hosts[0].paths[0].pathType'
          value: Prefix
        - name: 'app-template.ingress.main.hosts[0].paths[0].service.port'
          value: http
        - name: 'app-template.ingress.main.hosts[0].paths[0].service.identifier'
          value: main
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true