apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: media-lidarr
  namespace: openshift-gitops
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: lidarr
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: charts/lidarr
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      parameters:
        - name: cluster.top_level_domain
          value: {{ .Values.cluster.top_level_domain }}
        - name: cluster.name
          value: {{ .Values.cluster.name }}
        - name: cluster.admin_email
          value: {{ .Values.cluster.admin_email }}
        - name: 'app-template.route.main.hostsnames[0]'
          value: lidarr.apps.{{ .Values.cluster.name }}.{{ .Values.cluster.top_level_domain }}
        - name: app-template.controllers.main.containers.main.env.TZ
          value: {{ .Values.cluster.timezone }}
        - name: media.nfs.server
          value: {{ .Values.media.nfs.server }}
        - name: media.nfs.path
          value: {{ .Values.media.nfs.path }}
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true