config:
  storageClassName: "synology-iscsi"
  
app-template:
  controllers:
    main:
      type: statefulset
      annotations:
        reloader.stakater.com/auto: "true"
      labels:
        kasten/backup: "true"
      containers:
        main:
          image:
            # renovate: docker-image
            repository: housewrecker/gaps
            tag: x64-v0.10.4
            pullPolicy: IfNotPresent
          env:
            TZ: TIMEZONE

  serviceAccount:
    name: gaps-sa

  service:
    main:
      controller: main
      ports:
        http:
          port: 8484

  persistence:
    config:
      enabled: true
      existingClaim: gaps-config

    data:
      enabled: true
      existingClaim: gaps-data-volume
      globalMounts:
        - path: /data

  defaultPodOptions:
    labels:
      app: gaps
      version: 1.0.0
    securityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
        - 44
        - 109
        - 100
        - 65535
