config:
  storageClassName: "synology-iscsi"
  
app-template:
  controllers:
    main:
      type: statefulset
      annotations:
        reloader.stakater.com/auto: "true"
      labels:
        kasten/backup: "true"
      containers:
        main:
          image:
            # renovate: docker-image versioning=loose
            repository: ghcr.io/onedr0p/radarr
            tag: 5.4.6.8723
            pullPolicy: IfNotPresent
          env:
            TZ: TIMEZONE

  serviceAccount:
    name: radarr-sa

  service:
    main:
      controller: main
      ports:
        http:
          port: 7878

  persistence:
    config:
      enabled: true
      existingClaim: radarr-config

    data:
      enabled: true
      existingClaim: radarr-data-volume
      globalMounts:
        - path: /data

  defaultPodOptions:
    labels:
      sidecar.istio.io/inject: "true"
      app: radarr
      version: 1.0.0
    securityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
        - 44
        - 109
        - 100
        - 65535
