---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api-cert-tls
  namespace: openshift-config
spec:
  secretName: api-cert-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: api.openshift.$(SECRET_TLD)
  dnsNames: 
    - "api.openshift.$(SECRET_TLD)"
    - "api-int.openshift.$(SECRET_TLD)"
