apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: apps-wildcard-cert-tls
  namespace: openshift-ingress
spec:
  secretName: apps-wildcard-cert-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: apps.openshift.$(SECRET_TLD)
  dnsNames: 
    - "apps.openshift.$(SECRET_TLD)"
    - "*.apps.openshift.$(SECRET_TLD)"