apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: apps-wildcard-cert-tls
  namespace: openshift-ingress
spec:
  secretName: apps-wildcard-cert-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: apps.openshift.SECRET_TLD_PLACEHOLDER
  dnsNames: 
    - "apps.openshift.SECRET_TLD_PLACEHOLDER"
    - "*.apps.openshift.SECRET_TLD_PLACEHOLDER"
