---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./api.yaml
  - ./apps.yaml
# Disabled until i know certs work
#  - ./patch-apps-ingress.yaml
replacements:
- source:
    kind: Secret
    name: cert-manager-secrets
    namespace: cert-manager
    fieldPath: data.SECRET_TLD
  targets:
  - select:
      kind: Certificate
      name: api-cert-tls
    fieldPaths:
    - spec.commonName