---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./api.yaml
  - ./apps.yaml
# Disabled until i know certs work
# patches:
#  - target:
#       group: operator.openshift.io
#       version: v1
#       kind: IngressController
#       name: default
#       namespace: openshift-ingress-operator
#    path: patch-apps-ingress.yaml