apiVersion: hajimari.io/v1alpha1
kind: Application
metadata:
  name: bazarr
spec:
  name: Bazarr
  group: Media
  icon: simple-icons:subtitles
  url: https://bazarr.apps.{{ .Values.cluster.name }}.{{ .Values.cluster.top_level_domain }}
  info: Manages subtitles
  targetBlank: true
---
apiVersion: console.openshift.io/v1
kind: ConsoleLink
metadata:
  name: bazarr-application-menu-link
spec:
  href: https://bazarr.apps.{{ .Values.cluster.name }}.{{ .Values.cluster.top_level_domain }}
  location: ApplicationMenu
  applicationMenu:
    section: "Media Tools"
    imageURL: https://www.bazarr.media/assets/img/logo.png
  text: 'Bazarr'
---
apiVersion: console.openshift.io/v1
kind: ConsoleLink
metadata:
  name: bazarr-namespace-dashboard-link
spec:
  href: https://bazarr.apps.{{ .Values.cluster.name }}.{{ .Values.cluster.top_level_domain }}
  location: NamespaceDashboard
  namespaceDashboard:
    namespaces:
      - bazarr
  text: 'Access Application'
