kind: Route
apiVersion: route.openshift.io/v1
metadata:
  annotations:
    hajimari.io/enable: "true"
    hajimari.io/icon: "subtitles"
    hajimari.io/group: "Media"
    hajimari.io/info: "Manages and downloads subtitles"
    route.openshift.io/termination: "edge"
  name: bazarr
  namespace: bazarr
spec:
  host: bazarr.apps.{{ .Values.cluster.name }}.{{ .Values.cluster.top_level_domain }}
  path: /
  to:
    kind: Service
    name: media-bazarr
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
