apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
data:
  mosquitto.conf: |-
    per_listener_settings false
    listener 1883
    allow_anonymous true
    persistence true
    persistence_location /data
    autosave_interval 1800
    connection_messages false
    autosave_interval 60
