apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
data:
  mosquitto-0.yaml: |-
    per_listener_settings false
    listener 1883
    allow_anonymous true
    persistence true
    persistence_location /data
    autosave_interval 1800
    connection_messages false
    autosave_interval 60
  mosquitto-1.yaml: |-
    per_listener_settings false
    listener 1883
    allow_anonymous true
    persistence true
    persistence_location /data
    autosave_interval 1800
    connection_messages false
    autosave_interval 60

    connection broker0
    address mosquitto-0.mosquitto
    topic # both 0
