kind: Service
apiVersion: v1
metadata:
  name: mosquitto-0
spec:
  ports:
    - name: mqtt
      protocol: TCP
      port: 1883
      targetPort: 1883
  type: ClusterIP
  selector:
    app.kubernetes.io/component: main
    app.kubernetes.io/instance: mosquitto
    app.kubernetes.io/name: mosquitto
    statefulset.kubernetes.io/pod-name: mosquitto-0