kind: Service
apiVersion: v1
metadata:
  name: mqtt
  labels:
    keepalived-operator.redhat-cop.io/keepalivedgroup: "keepalived-operator/{{ .Values.network.mqtt.keepalivegroup }}"
  annotations:
    coredns.io/hostname: mqtt
spec:
  externalIPs:
    - {{ .Values.network.mqtt.externalIP }}
  ports:
    - name: mqtt
      protocol: TCP
      port: 1883
      targetPort: 1883
  internalTrafficPolicy: Cluster
  type: ClusterIP
  selector:
    app.kubernetes.io/component: main
    app.kubernetes.io/instance: mosquitto
    app.kubernetes.io/name: mosquitto
