---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: readarr-config
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: synology-iscsi
  resources:
    requests:
      storage: 15Gi