kind: Route
apiVersion: route.openshift.io/v1
metadata:
  annotations:
    forecastle.stakater.com/expose: "true"
    forecastle.stakater.com/icon: "https://raw.githubusercontent.com/Readarr/Readarr/develop/Logo/400.png"
    forecastle.stakater.com/appName: "readarr"
    forecastle.stakater.com/group: "Media"
    route.openshift.io/termination: "edge"
  name: readarr
  namespace: readarr
spec:
  host: readarr.apps.{{ .Values.cluster.name }}.{{ .Values.cluster.top_level_domain }}
  path: /
  to:
    kind: Service
    name: media-readarr
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
