apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  generateName: openshift-kube-descheduler-operator-
  name: openshift-kube-descheduler-operator-cluster
  namespace: openshift-kube-descheduler-operator
spec:
  targetNamespaces:
    - openshift-kube-descheduler-operator
  upgradeStrategy: Default
