---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./secret.yaml
  - ./letsencrypt-production.yaml
  - ./letsencrypt-staging.yaml
replacements:
  - path: secret.yaml
    version: v1
    kind: Secret
    fieldSpecs:
      - path: data.AWS_ACCESS_KEY_ID
        create: true
        from:
          secretKeyRef:
            name: cert-manager-secrets
            key: AWS_ACCESS_KEY_ID