---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: static-pool
  namespace: metallb-system
spec:
  avoidBuggyIPs: true
  addresses:
    - {{ .Values.network.plexIP }}/32
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: static-pool-advertisement
  namespace: metallb-system
spec:
    ipAddressPools:
    - name: static-pool
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: auto-pool
  namespace: metallb-system
spec:
  autoAssign: false
  avoidBuggyIPs: true
  addresses:
  - {{ .Values.network.startIP }}-{{ .Values.network.endIP }}
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: auto-pool-advertisement
  namespace: metallb-system
spec:
    ipAddressPools:
    - name: static-pool