apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: home-hajimari
  namespace: openshift-gitops
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: hajimari
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: charts/hajimari
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      parameters:
        - name: cluster.top_level_domain
          value: {{ .Values.cluster.top_level_domain }}
        - name: cluster.name
          value: {{ .Values.cluster.name }}
        - name: cluster.admin_email
          value: {{ .Values.cluster.admin_email }}
        - name: app-template.controllers.main.containers.main.env.TZ
          value: {{ .Values.cluster.timezone }}
        - name: media.nfs.server
          value: {{ .Values.media.nfs.server }}
        - name: media.nfs.path
          value: {{ .Values.media.nfs.path }}
        - name: hajimari.globalBookmarks
          value: |
            - group: Communicate
              bookmarks:
                - name: Discord
                  url: 'https://discord.com'
                - name: Gmail
                  url: 'http://gmail.com'
                - name: Slack
                  url: 'https://slack.com/signin'
            - group: Cloud
              bookmarks:
                - name: Box
                  url: 'https://box.com'
                - name: Dropbox
                  url: 'https://dropbox.com'
                - name: Drive
                  url: 'https://drive.google.com'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true