apiVersion: hajimari.io/v1alpha1
kind: Application
metadata:
  name: nas
  namespace: hajimari
spec:
  name: Synology
  group: Infrastructure
  icon: nas
  url: http://nas.{{ .Values.cluster.top_level_domain }}
  info: Storage
---
apiVersion: hajimari.io/v1alpha1
kind: Application
metadata:
  name: homeassistant
  namespace: hajimari
spec:
  name: HomeAssistant
  group: Home Automation
  icon: home-assistant
  url: http://homeassistant.{{ .Values.cluster.top_level_domain }}:8123
  info: Home automation
---
apiVersion: hajimari.io/v1alpha1
kind: Application
metadata:
  name: valetudo
  namespace: hajimari
spec:
  name: Vacuum
  group: Home Automation
  icon: robot-vacuum
  url: http://valetudo.{{ .Values.cluster.top_level_domain }}
  info: Home automation
---
apiVersion: hajimari.io/v1alpha1
kind: Application
metadata:
  name: unifi
  namespace: hajimari
spec:
  name: UniFi
  group: Infrastructure
  icon: arcticons:unifi-network
  url: http://unifi.{{ .Values.cluster.top_level_domain }}:8443
  info: Manage WIFI 
---
apiVersion: hajimari.io/v1alpha1
kind: Application
metadata:
  name: firewall
  namespace: hajimari
spec:
  name: Router
  group: Infrastructure
  icon: router-network
  url: http://firewall.{{ .Values.cluster.top_level_domain }}
  info: Manage firewall
---
apiVersion: hajimari.io/v1alpha1
kind: Application
metadata:
  name: switch
  namespace: hajimari
spec:
  name: Main switch
  group: Infrastructure
  icon: material-symbols:switch
  url: http://switch.{{ .Values.cluster.top_level_domain }}
  info: Manage switch
---
apiVersion: hajimari.io/v1alpha1
kind: Application
metadata:
  name: poe-switch
  namespace: hajimari
spec:
  name: PoE switch
  group: Infrastructure
  icon: material-symbols:switch
  url: http://poe-switch.{{ .Values.cluster.top_level_domain }}
  info: Manage switch